### ISSUE TITLE
how to transfer the omas to imas in STEP

### ISSUE THREAD

**Issue by shis316** [gafusion/omas#295]
When I use STEP(Oct 2023) in OMFIT(master_v3) to transfer the omas to imas, it shows:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/fusion/projects/codes/atom/omfit_v3.x/atom_iris_test/mambaforge/envs/3.2023.35.0/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/fusion/projects/codes/atom/omfit_v3.x/atom_iris_test/OMFIT-source_3.2023.50/omfit/omfit_classes/OMFITx.py", line 1534, in <lambda>
    command=lambda: buttonClick(btt, lambda: manage_user_errors(command, reportUsersErrorByEmail=True), updateGUI),
  File "/fusion/projects/codes/atom/omfit_v3.x/atom_iris_test/OMFIT-source_3.2023.50/omfit/omfit_classes/OMFITx.py", line 1516, in buttonClick
    command()
  File "/fusion/projects/codes/atom/omfit_v3.x/atom_iris_test/OMFIT-source_3.2023.50/omfit/omfit_classes/OMFITx.py", line 1534, in <lambda>
    command=lambda: buttonClick(btt, lambda: manage_user_errors(command, reportUsersErrorByEmail=True), updateGUI),
  File "/fusion/projects/codes/atom/omfit_v3.x/atom_iris_test/OMFIT-source_3.2023.50/omfit/omfit_classes/OMFITx.py", line 4624, in manage_user_errors
    tmp = command(**kw)
  File "/local-scratch/shis/OMFIT/OMFIT_2024-02-25_22_41_12_212031/project/objects/file_2024-02-27__09_30/57__777203/imasGUI.py", line 21, in save
    new=True,
  File "/fusion/projects/codes/atom/omfit_v3.x/atom_iris_test/OMFIT-source_3.2023.50/omfit/omfit_classes/omfit_omas.py", line 288, in save_omas_imas_remote
    return _base_omas_remote(serverPicker, 'save_omas_imas', **kw)
  File "/fusion/projects/codes/atom/omfit_v3.x/atom_iris_test/OMFIT-source_3.2023.50/omfit/omfit_classes/omfit_omas.py", line 275, in _base_omas_remote
    forceRemote=forceRemote,
  File "/fusion/projects/codes/atom/omfit_v3.x/atom_iris_test/OMFIT-source_3.2023.50/omfit/omfit_classes/OMFITx.py", line 6929, in remote_python
    **kw,
  File "/fusion/projects/codes/atom/omfit_v3.x/atom_iris_test/OMFIT-source_3.2023.50/omfit/omfit_classes/OMFITx.py", line 6684, in executable
    initWorkdir(module_root, clean=clean, server=server, tunnel=tunnel, workdir=workdir, remotedir=remotedir, quiet=quiet)
  File "/fusion/projects/codes/atom/omfit_v3.x/atom_iris_test/OMFIT-source_3.2023.50/omfit/omfit_classes/OMFITx.py", line 6486, in initWorkdir
    use_bang_command=False,
  File "/fusion/projects/codes/atom/omfit_v3.x/atom_iris_test/OMFIT-source_3.2023.50/omfit/omfit_classes/OMFITx.py", line 5855, in remote_execute
    username, server, port = setup_ssh_tunnel(server0, tunnel0, forceRemote=forceRemote, ssh_path=SERVER['localhost'].get('ssh_path', None))
  File "/fusion/projects/codes/atom/omfit_v3.x/atom_iris_test/OMFIT-source_3.2023.50/omfit/omfit_classes/utils_base.py", line 2043, in setup_ssh_tunnel
    f'Start OMFIT and specify username explicitly under `File > Preferences > Remote Servers` for connection to server `{server0}`'
omfit_classes.exceptions_omfit.OMFITexception: Start OMFIT and specify username explicitly under `File > Preferences > Remote Servers` for connection to server `@login.eufus.eu:22`
```
I don't understand why this happened and how to solve this problem. Thanks a lot

**Comment by orso82** [comment]
If you look closely at the error, it says: `Start OMFIT and specify username explicitly under `File > Preferences > Remote Servers` for connection to server `@login.eufus.eu:22` So it looks like you have to populate your 'ITM_username'

**Comment by shis316** [comment]
Thanks orso, yes, then I corrected the service as itm_gateway Server as g2sshen@login.eufu.eu:22, I found in my gateway account, there is an empty dictionary:  /afs/eufus.eu/user/g/g2sshen/public/imasdb/ITER/3/0. Maybe this is because I use STEP to transfer, there is just one time slice. I will try to use kineticEFITtime to generate the IMAS.
