### ISSUE TITLE
Updates to machine_mapping break MAST machine mappings. 

### ISSUE THREAD

**Issue by jmcclena** [gafusion/omas#305]
the following error 

```
pf_active.coil.: issue:TypeError("'topic' is an invalid keyword argument for print()")
magnetics.b_field_pol_probe.: issue:TypeError("'topic' is an invalid keyword argument for print()")
magnetics.flux_loop.: issue:TypeError("'topic' is an invalid keyword argument for print()")

Exception in script of module OMFIT['EFITtime']:
Error in "update_keqdsk_from_omas.py" at line  97
    ods.physics_equilibrium_form_constraints(
omas.omas_core.OmasDynamicException: Problem with ip: Error dynamic fetching of `magnetics.ip.0.data` for {'machine': 'mast', 'pulse': 45272, 'options': {}, 'branch': '', 'user_machine_mappings': None}: TypeError("'topic' is an invalid keyword argument for print()")


Press <F6> to see full error report...

Traceback (most recent call last):
  File "/home/ql0457/omas/omas/omas_core.py", line 1303, in __getitem__
    value = self.dynamic.__getitem__(location)
  File "/home/ql0457/omas/omas/omas_machine.py", line 712, in __getitem__
    ods, _ = machine_to_omas(
  File "/home/ql0457/omas/omas/omas_machine.py", line 151, in machine_to_omas
    return resolve_mapped(ods, machine, pulse,  mappings, location, idm, options_with_defaults, branch, cache=cache)
  File "/home/ql0457/omas/omas/omas_machine.py", line 219, in resolve_mapped
    printe(f"MAST is currently not supported because of UDA", topic='machine')
  File "/home/ql0457/omas/omas/omas_utils.py", line 218, in printe
    print(*objects, **kw)
TypeError: 'topic' is an invalid keyword argument for print()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ql0457/omas/omas/omas_physics.py", line 711, in equilibrium_form_constraints
    data = ods['magnetics.ip.0.data']
  File "/home/ql0457/omas/omas/omas_core.py", line 1324, in __getitem__
    return value.__getitem__(key[1:], cocos_and_coords)
  File "/home/ql0457/omas/omas/omas_core.py", line 1324, in __getitem__
    return value.__getitem__(key[1:], cocos_and_coords)
  File "/home/ql0457/omas/omas/omas_core.py", line 1324, in __getitem__
    return value.__getitem__(key[1:], cocos_and_coords)
  File "/home/ql0457/omas/omas/omas_core.py", line 1305, in __getitem__
    raise OmasDynamicException(f'Error dynamic fetching of `{location}` for {self.dynamic.kw}: {repr(_excp)}')
omas.omas_core.OmasDynamicException: Error dynamic fetching of `magnetics.ip.0.data` for {'machine': 'mast', 'pulse': 45272, 'options': {}, 'branch': '', 'user_machine_mappings': None}: TypeError("'topic' is an invalid keyword argument for print()")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/common/projects2/physics/omfit/atom-freia-michal/OMFIT-source_3.2023.11/omfit/omfit_classes/OMFITx.py", line 4624, in manage_user_errors
    tmp = command(**kw)
  File "/tmp/ql0457/OMFIT/OMFIT_2024-04-05_16_30_24_044165/project/objects/file_2024-04-05__16_33/52__441546/runGUI.py", line 765, in <lambda>
    lambda: root['SCRIPTS']['MAST']['update_keqdsk_from_omas'].run(
  File "/common/projects2/physics/omfit/atom-freia-michal/OMFIT-source_3.2023.11/omfit/omfit_classes/omfit_python.py", line 1105, in run
    result = self.__run__(**kw)
  File "/common/projects2/physics/omfit/atom-freia-michal/OMFIT-source_3.2023.11/omfit/omfit_classes/omfit_python.py", line 949, in __run__
    tmp = execGlobLoc(
  File "/common/projects2/physics/omfit/atom-freia-michal/OMFIT-source_3.2023.11/omfit/omfit_classes/omfit_python.py", line 129, in f_locked
    return f(*args, **kw)
  File "/common/projects2/physics/omfit/atom-freia-michal/OMFIT-source_3.2023.11/omfit/omfit_classes/omfit_python.py", line 376, in execGlobLoc
    exec(compile(execString, filename, "exec"), GlobLoc)
  File "/tmp/ql0457/OMFIT/OMFIT_2024-04-05_16_30_24_044165/project/objects/file_2024-04-05__16_33/51__381373/update_keqdsk_from_omas.py", line 97, in <module>
    ods.physics_equilibrium_form_constraints(
  File "/home/ql0457/omas/omas/omas_physics.py", line 731, in equilibrium_form_constraints
    raise _excp.__class__(f'Problem with ip: {_excp}')
omas.omas_core.OmasDynamicException: Problem with ip: Error dynamic fetching of `magnetics.ip.0.data` for {'machine': 'mast', 'pulse': 45272, 'options': {}, 'branch': '', 'user_machine_mappings': None}: TypeError("'topic' is an invalid keyword argument for print()")
```

**Comment by jmcclena** [comment]
Fixing the omas print on https://github.com/gafusion/omas/blob/c3b538b04b22bff901cf61ba8d0bb76a38528c2a/omas/omas_machine.py#L219C1-L219C87 leads to new errors.
