### ISSUE TITLE
loading an IDS from a previous data versio can fail

### ISSUE THREAD

**Issue by jsferreira** [gafusion/omas#54]
Recently I was trying to load IDSs written with an older data version than the current one, and found this issue:

at the ITM/gateway try:

```bash
module load imasenv
module load omfit
python -c "from omas import *; ods = load_omas_imas(shot=92436,run=172,machine=u'jet',user=u'g2jofe',imas_version=u'3.20.0')"
```
but it fails with:

```python
core_transport.model.7.profiles_1d.0.ion.2.element.0.multiplicity is in OBSOLESCENT state
core_transport.model.8.profiles_1d.0.ion.0.element.0.multiplicity is in OBSOLESCENT state
core_transport.model.8.profiles_1d.0.ion.1.element.0.multiplicity is in OBSOLESCENT state
core_transport.model.8.profiles_1d.0.ion.2.element.0.multiplicity is in OBSOLESCENT state
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/afs/gw/switm/omfit/atom/omas/omas/omas_imas.py", line 460, in load_omas_imas
    h = h[step]
  File "/afs/gw/switm/omfit/atom/omas/omas/omas_core.py", line 580, in __getitem__
    cocos=self.cocos, cocosio=self.cocosio, coordsio=self.coordsio))
  File "/afs/gw/switm/omfit/atom/omas/omas/omas_core.py", line 423, in __setitem__
    spaces + '^' * len(structure_key) + '\n' + '%s' % options)
LookupError: `ec_antennas.antenna.0.power` is not a valid IMAS 3.21.0 location
                                    ^^^^^
Did you mean: [u'launching_angle_pol', u'launching_position', u'launching_angle_tor', u'name', u'frequency_error_lower', u'power_launched', u'beam', u'frequency', u'frequency_error_upper', u'identifier', u'frequency_error_index', u'mode']
```
which should not happen since I requested a load with imas_version=u'3.20.0'

My 92436/172 pulse was created with the IMAS data structure 3.20.0.

The **power**  in ec_antennas.antenna.%.**power**, nbi.unit.%.**power** or ic_antennas.antenna.%.**power** changed to **power_launched** in 3.21.0, the current/latest data structure.

Seems that imas_version is not propagated to the consistency check loop.

**Comment by orso82** [comment]
@jsferreira thank you for the error report 👍 
Please let me know if you still have problems!
